Repository SOMAS2020/SOMAS2020, pull requests merged in 2020-12, with the labels that each got.

#19 [INFRA/CORE] Add rule against `panic` and `die`.
  docs/SETUP.md
Labels: CORE, documentation

#14 [INFRA/RULES] Added basic implementation of matrix based rules
  go.mod
  go.sum
  internal/clients/team3/client.go
  internal/common/client.go
  internal/common/client_test.go
  internal/common/rules/globalruleregistration.go
  internal/common/rules/globalruleregistration_test.go
  internal/common/rules/globalrulescache.go
  internal/common/rules/globalrulescache_test.go
  internal/common/rules/globalvariablecache.go
  internal/common/rules/globalvariablecache_test.go
  internal/common/rules/globalvariableregistration.go
  internal/common/rules/globalvariableregistration_test.go
  internal/common/rules/rulematrix.go
Labels: RULES

#22 [INFRA/CORE] Attempted to fix warning for PRs that modify protected folders
  .github/workflows/protected_folder.yml
Labels: CORE, enhancement

#26 [INFRA/CORE] Protected folders V2
  .github/workflows/protected_folder.yml
Labels: CORE, enhancement

#28 [INFRA/CORE] Fixed file exclusion in protected action
  .github/workflows/protected_folder.yml
Labels: CORE, enhancement

#30 [INFRA/CORE] Fixed protected guard for non fork PRs
  .github/workflows/protected_folder.yml
Labels: CORE, enhancement

#32 [INFRA/CORE] Final protected guard warning
  .github/workflows/protected_folder.yml
Labels: CORE, enhancement

#34 [INFRA/CORE] Switched to new action that may work with fork PRs
  .github/workflows/protected_folder.yml
Labels: CORE, enhancement

#37 [INFRA/CORE] redefine server interface to have an EntryPoint
  internal/common/game.go
  internal/server/helper.go
  internal/server/helper_test.go
  internal/server/server.go
  internal/server/server_test.go
  main.go
Labels: CORE, enhancement

#43 [INFRA/CORE] Use errors.Errorf
  docs/SETUP.md
  go.mod
  go.sum
  internal/common/client.go
  internal/common/rules/globalrulescache.go
  internal/common/rules/globalvariablecache.go
  internal/server/server.go
  internal/server/server_test.go
  main.go
Labels: CORE

#40 [INFRA/CORE] Add core components according to spec
  internal/clients/team1/client.go
  internal/clients/team2/client.go
  internal/clients/team3/client.go
  internal/clients/team4/client.go
  internal/clients/team5/client.go
  internal/clients/team6/client.go
  internal/common/client.go
  internal/common/config/config.go
  internal/common/game.go
  internal/common/shared/lifestatus.go
  internal/common/shared/shared.go
  internal/server/disaster.go
  internal/server/helper.go
  internal/server/helper_test.go
  internal/server/iifo.go
  internal/server/iigo.go
  internal/server/iito.go
  internal/server/server.go
  internal/server/server_test.go
  internal/server/turn.go
  internal/server/turn_test.go
  main.go
Labels: CORE

#42 [INFRA/CORE] Implement Actions + some tidying up
  go.mod
  go.sum
  internal/clients/team1/client.go
  internal/clients/team2/client.go
  internal/clients/team3/client.go
  internal/clients/team4/client.go
  internal/clients/team5/client.go
  internal/clients/team6/client.go
  internal/common/action.go
  internal/common/client.go
  internal/common/game.go
  internal/server/iifo.go
  internal/server/iigo.go
  internal/server/iito.go
  internal/server/turn.go
Labels: CORE

#45 [INFRA/CORE] added base_client implementation
  internal/clients/team1/client.go
  internal/clients/team2/client.go
  internal/clients/team3/client.go
  internal/clients/team4/client.go
  internal/clients/team5/client.go
  internal/clients/team6/client.go
  internal/common/base_client.go
  internal/common/client.go
  internal/server/clientreg_test.go
Labels: CORE

#90 [INFRA/CORE] Added .gitattributes file
  .gitattributes
Labels: CORE, enhancement
